### Create Movie Session
POST http://localhost:8080/movie-sessions
Content-Type: application/json

{
  "date": "2025-04-16",
  "time": "14:30:00",
  "movieId": "123e4567-e89b-12d3-a456-426614174000",
  "screenId": "123e4567-e89b-12d3-a456-426614174001",
  "col": 25,
  "row": 50
}

### Book seat
POST http://localhost:8080/movie-sessions/9a06ffc9-81f8-438d-8424-0d8e3b708a61/bookings
Content-Type: application/json

{
  "customerId": "a07ef105-35da-4a88-a0a5-b0372ac98e88",
  "requestedSeats": [
    {
      "col": 10,
      "row": 20
    },
    {
      "col": 10,
      "row": 21
    }
  ]
}

### Get by ref
GET http://localhost:8080/seats/32e5562a-aa2b-40d4-9daa-8542e8fe22db