### Create Movie Session
POST http://localhost:8080/movie-sessions
Content-Type: application/json

{
  "date": "2025-04-16",
  "time": "14:30:00",
  "movieId": "123e4567-e89b-12d3-a456-426614174000",
  "screenId": "123e4567-e89b-12d3-a456-426614174001",
  "col": 25,
  "row": 50
}

### Book Seats
POST http://localhost:8080/movie-sessions/2aec0b67-08af-4241-9834-9dfb2fa1db98/bookings
Content-Type: application/json

{
  "customerId": "a07ef105-35da-4a88-a0a5-b0372ac98e88",
  "requestedSeats": [
    {
      "col": 11,
      "row": 20
    },
    {
      "col": 11,
      "row": 21
    }
  ]
}

### Get Booking by Code
GET http://localhost:8080/movie-sessions/2aec0b67-08af-4241-9834-9dfb2fa1db98/bookings/1963FD42903